###########
# site.title

title: EXME
description: a minimal, text focused blog theme

# Untuk custom domain
url: "https://farhan.js.org"
baseurl: ""  # kosongkan jika tidak pakai subfolder

#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

permalink: /blog/:slug
timezone: Asia/Jakarta
future: false

exclude:
  - README.md
  - LICENSE.md
  - vendor

Blog: blog
Life: life
Crypto: crypto

# Add general links to site pages here
links:
  # Resume: /assets/resume.pdf

# Add links for more focus here
special_links:
  # "Search": https://duckduckgo.com
